// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCwVFyh7SVwhzti4m7I0pGK_Yn3RykZJs',
    appId: '1:271632214452:web:0b7bcbf6c617f8db27aae1',
    messagingSenderId: '271632214452',
    projectId: 'test-c4f67',
    authDomain: 'test-c4f67.firebaseapp.com',
    storageBucket: 'test-c4f67.firebasestorage.app',
    measurementId: 'G-XDFPZ3HX4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLWSHuiiPR2l3h2svPdnPmmwp3e-geXqs',
    appId: '1:271632214452:android:719bfcbe45376acd27aae1',
    messagingSenderId: '271632214452',
    projectId: 'test-c4f67',
    storageBucket: 'test-c4f67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcBHWyfxa9Adat6pwdQ-dgvhpWVgtgxkY',
    appId: '1:271632214452:ios:18eedf5e80ddab3427aae1',
    messagingSenderId: '271632214452',
    projectId: 'test-c4f67',
    storageBucket: 'test-c4f67.firebasestorage.app',
    iosBundleId: 'com.example.mytest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcBHWyfxa9Adat6pwdQ-dgvhpWVgtgxkY',
    appId: '1:271632214452:ios:18eedf5e80ddab3427aae1',
    messagingSenderId: '271632214452',
    projectId: 'test-c4f67',
    storageBucket: 'test-c4f67.firebasestorage.app',
    iosBundleId: 'com.example.mytest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCwVFyh7SVwhzti4m7I0pGK_Yn3RykZJs',
    appId: '1:271632214452:web:ca1f7b8630c995ca27aae1',
    messagingSenderId: '271632214452',
    projectId: 'test-c4f67',
    authDomain: 'test-c4f67.firebaseapp.com',
    storageBucket: 'test-c4f67.firebasestorage.app',
    measurementId: 'G-DMDQ6BTLNN',
  );
}
